export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number;
  veg: boolean;
  special?: boolean; // Chef's Special, marked "(S)" on the printed menu
};

export type MenuCategory = {
  id: string;
  name: string;
  note?: string;
  items: MenuItem[];
};

// Digitized from the restaurant's printed menu (The Garden 190726.pdf).
// Prices are in INR and exclude local taxes, applied at pickup.
// Alcoholic beverages (wine/beer/spirits/cocktails) are intentionally not
// included in online ordering — dine-in / in-person only.
export const menu: MenuCategory[] = [
  {
    id: "soups",
    name: "Soups",
    items: [
      { id: "soup-cream-tomato", name: "Cream of Tomato", description: "Rich taste of fresh plum tomatoes & a dash of cream topping.", price: 175, veg: true },
      { id: "soup-cream-mushroom", name: "Cream of Mushroom", description: "Fresh mushrooms sauted, pureed & topped with fresh cream.", price: 195, veg: true },
      { id: "soup-cream-spinach", name: "Cream of Spinach", description: "Spinach soup flavoured with herbs and served with a touch of cream.", price: 195, veg: true },
      { id: "soup-sweetcorn-veg", name: "Sweetcorn Vegetable", description: "A classic soup made with cream style corn.", price: 180, veg: true },
      { id: "soup-veg-manchow", name: "Vegetable Manchow", description: "A soup prepared with vegetables, flavoured with soy sauce, garlic & chilli.", price: 180, veg: true },
      { id: "soup-potato-garlic", name: "Potato Garlic", description: "Potatoes are roasted & pureed to make a hearty creamy soup.", price: 190, veg: true },
      { id: "soup-goan-macaroni", name: "Goan Macaroni", description: "Macaroni boiled in a Goan vegetable broth.", price: 200, veg: true },
      { id: "soup-hot-sour-veg", name: "Hot 'n' Sour Vegetable", description: "A spicy & tangy vegetable soup.", price: 190, veg: true },
      { id: "soup-cream-chicken", name: "Cream of Chicken", description: "Thick, creamy soup made with chicken stock.", price: 200, veg: false },
      { id: "soup-hot-sour-chicken", name: "Hot 'n' Sour Chicken", description: "A spicy & tangy soup with shredded chicken.", price: 200, veg: false },
      { id: "soup-sweetcorn-chicken", name: "Sweet Corn Chicken", description: "Thick, creamy soup made with cream style corn & chicken stock.", price: 210, veg: false },
      { id: "soup-chicken-manchow", name: "Chicken Manchow", description: "A dark brown soup flavoured with soy sauce, garlic & chilli.", price: 210, veg: false },
      { id: "soup-chicken-spinach", name: "Chicken & Spinach", description: "A comforting soup made with succulent chicken & fresh spinach.", price: 210, veg: false },
      { id: "soup-sweetcorn-prawn", name: "Sweet Corn Prawn", description: "Thick, creamy soup made with cream style corn & stock.", price: 210, veg: false },
    ],
  },
  {
    id: "salads-raitas",
    name: "Salads & Raitas",
    items: [
      { id: "salad-green", name: "Green Salad", description: "Onion, cucumber, carrot, tomatoes topped with a slice of lemon.", price: 175, veg: true },
      { id: "salad-tossed", name: "Tossed Salad", description: "Cubed veg & fresh cut lettuce dressed with a squeeze of lime and herbs.", price: 190, veg: true },
      { id: "salad-goan", name: "Goan Salad", description: "Mixed vegetables salad with a dash of Goan vinegar.", price: 190, veg: true },
      { id: "salad-crispy-noodle", name: "Crispy Noodle Salad", description: "Crispy noodles, shredded vegetables and peanuts tossed in a sweet chilly dressing.", price: 330, veg: true },
      { id: "salad-chicken-hawaiian", name: "Chicken Hawaiian Salad", description: "Chicken and pineapple mixed in mayonnaise & seasoned well.", price: 365, veg: false },
      { id: "raita-veg", name: "Veg Raita", description: "Indian mixed vegetable salad with yogurt dressing.", price: 190, veg: true },
      { id: "raita-pineapple", name: "Pineapple Raita", description: "A perfect blend of pineapple chunks & yogurt, excellent for cooling spicy dishes.", price: 220, veg: true },
      { id: "raita-beetroot", name: "Beetroot Raita", description: "Tender beetroot pieces mixed with yogurt, crushed peanuts & seasoned with mustard seeds & curry leaves.", price: 250, veg: true },
    ],
  },
  {
    id: "chaat",
    name: "Chaat (Street Food)",
    items: [
      { id: "chaat-aloo-tikki", name: "Aloo Tikki Chaat", description: "Potato patties topped with a tangy-sweet tamarind chutney, green chutney & curd.", price: 370, veg: true },
      { id: "chaat-papdi", name: "Papdi Chaat", description: "Indian chaat snack made with crisp fried puris, sweet sour spicy chutneys & sev.", price: 290, veg: true },
      { id: "chaat-ragda-puri", name: "Ragda Puri Chaat", description: "Indian street food made with puri, white pea gravy, tomato, onion and chutneys.", price: 290, veg: true },
      { id: "chaat-shev-batata-dahi-puri", name: "Shev Batata Dahi Puri", description: "Crispy puri topped with various chutneys, masalas, boiled potatoes and yogurt.", price: 290, veg: true },
      { id: "chaat-aam-palak-patta", name: "Aam Palak Patta Chaat", description: "Crispy spinach with spicy green chutney, tamarind & masala mango drizzle.", price: 370, veg: true },
      { id: "chaat-platter", name: "Chaat Platter", description: "Papdi chaat, shev batata dahi puri, aloo tikki chaat & aam palak patta chaat.", price: 600, veg: true },
    ],
  },
  {
    id: "starters",
    name: "Starters & Snacks",
    note: "Fried Prawns are priced as per market rate — ask our team when you call in your order.",
    items: [
      { id: "starter-masala-papad", name: "Masala Papad", description: "Roasted papad topped with chopped tomato, onion & cucumber.", price: 270, veg: true },
      { id: "starter-chilli-paneer", name: "Indian Chilli Paneer", description: "A very popular Indo-Chinese dish.", price: 400, veg: true },
      { id: "starter-dahi-kebab", name: "Dahi Kebab", description: "Spiced thick yogurt mixed with paneer served with mint sauce.", price: 370, veg: true },
      { id: "starter-mushroom-galouti", name: "Mushroom Galouti Kebab", description: "Vegetarian version of an age-old galouti kebab designed to melt in your mouth.", price: 380, veg: true },
      { id: "starter-hara-bhara-kebab", name: "Hara Bhara Kebab", description: "Vegetable cutlet snack prepared with spinach and green peas.", price: 400, veg: true },
      { id: "starter-stuffed-mushrooms", name: "Stuffed Mushrooms", description: "Mushrooms stuffed with cheese & spinach.", price: 370, veg: true },
      { id: "starter-potato-65", name: "Potato 65", description: "An Indian favourite, hot and tangy sauce.", price: 380, veg: true },
      { id: "starter-paneer-chatapata", name: "Paneer Chatapata", description: "Soft paneer chunks tossed in a sweet, spicy, tangy masala.", price: 420, veg: true },
      { id: "starter-kurkuri-bhindi", name: "Kurkuri Bhindi", description: "Spicy, tangy, crispy fries made with tender okra pods, gram flour and spices.", price: 320, veg: true },
      { id: "starter-onion-bhajiya", name: "Onion Bhajiya", description: "Battered & deep fried snack made from onion.", price: 340, veg: true },
      { id: "starter-veg-platter", name: "Veg Platter", description: "Hara bhara kebab, dahi kebab, paneer tikka and tameta na bhajiya, served with mint chutney and in-house baked pitta bread.", price: 600, veg: true },
      { id: "starter-tameta-bhajiya", name: "Tameta Na Bhajiya", description: "A Surati specialty, tomatoes topped with bright green chutney, coated in spicy chickpea flour and deep fried.", price: 320, veg: true },
      { id: "starter-french-fries", name: "French Fries", description: "Bowl of fried potato strips.", price: 320, veg: true },
      { id: "starter-peanut-masala", name: "Peanut Masala", description: "A lip-smacking snack from South India.", price: 270, veg: true },
      { id: "starter-honey-chilly-potatoes", name: "Honey Chilly Potatoes", description: "An Indo-Chinese street food made of crispy fried potato tossed in a sweet, spicy, and tangy honey-chilli sauce.", price: 380, veg: true },
      { id: "starter-stuffed-squids", name: "Stuffed Squids", description: "Whole squid stuffed with a spicy mixture made with prawns.", price: 530, veg: false, special: true },
      { id: "starter-fiery-garlic-squid", name: "Fiery Garlic Squid", description: "Deep-fried squid rings tossed in chillies and garlic.", price: 530, veg: false },
      { id: "starter-badi-prawns", name: "Badi Prawns", description: "Prawn fritters made of 'Badi', a sun-dried lentil dumpling, a key ingredient in Odisha.", price: 470, veg: false },
      { id: "starter-andhra-fish", name: "Andhra Fish", description: "Pan-fried steak of Goan chonak coated with spices on a bed of mash potato.", price: 560, veg: false },
      { id: "starter-mackerel-fry", name: "Mackerel Fry", description: "2 pieces of mackerel served with salad. Choice of butter garlic, butter lemon or masala fry.", price: 420, veg: false },
      { id: "starter-lahori-fish-fry", name: "Lahori Fish Fry", description: "Spicy, crispy fish made with boneless fish pieces coated in spices and deep-fried.", price: 540, veg: false },
      { id: "starter-fish-cutlets", name: "Fish Cutlets", description: "6 cutlets served with salad.", price: 400, veg: false },
      { id: "starter-fish-fingers", name: "Fish Fingers", description: "Fried breaded fish strips.", price: 500, veg: false },
      { id: "starter-murgh-banjara-kebab", name: "Murgh Banjara Kebab", description: "Spicy chicken kebab fully loaded with coriander, mint and cumin.", price: 430, veg: false, special: true },
      { id: "starter-chapli-kebab", name: "Chapli Kebab", description: "Spices mixed with chicken mince made into cutlets. Served with fresh bread & hummus.", price: 470, veg: false },
      { id: "starter-chicken-lollipop", name: "Chicken Lollipop", description: "Fried pulled chicken wings.", price: 420, veg: false },
      { id: "starter-nellore-chicken", name: "Nellore Chicken", description: "Dry chicken starter made with freshly ground spices.", price: 420, veg: false },
      { id: "starter-chicken-65", name: "Chicken 65", description: "An Indian favourite, hot and tangy sauce.", price: 420, veg: false },
      { id: "starter-satay-chicken", name: "Satay Chicken", description: "Pieces of chicken pan fried in peanut butter sauce.", price: 450, veg: false },
      { id: "starter-qureshi-kebab", name: "Qureshi Kebab", description: "Smoke infused, spicy, pan-fried mutton mince kebabs.", price: 520, veg: false },
      { id: "starter-nargisi-kebab", name: "Nargisi Kebab", description: "Perfectly spiced mutton keema wrapped around a hard boiled egg.", price: 550, veg: false },
    ],
  },
  {
    id: "tandoori",
    name: "Tandoori",
    items: [
      { id: "tandoori-gobi-tikka", name: "Gobi Tikka", description: "Marinated florets of cauliflower baked in the tandoor.", price: 400, veg: true },
      { id: "tandoori-mushroom-tikka", name: "Mushroom Tikka", description: "Marinated mushrooms baked in the tandoor.", price: 360, veg: true },
      { id: "tandoori-paneer-tikka", name: "Paneer Tikka", description: "Soft, juicy chunks of paneer marinated in spices and baked in the tandoor.", price: 420, veg: true },
      { id: "tandoori-dum-aloo-kebab", name: "Dum Aloo Kebab", description: "Stuffed potato covered in tandoori paste & slow cooked in clay oven.", price: 430, veg: true },
      { id: "tandoori-paneer-achari-kebab", name: "Paneer Achari Kebab", description: "Very similar to paneer tikka but with a strong pickle flavour.", price: 430, veg: true },
      { id: "tandoori-chicken-seekh-kebab", name: "Chicken Seekh Kebab", description: "Minced chicken seasoned with spices cooked in the tandoor.", price: 460, veg: false },
      { id: "tandoori-kali-mirch-murgh-kebab", name: "Kali Mirch Murgh Kebab", description: "Half tandoori chicken coated in a marinade of black pepper & curry leaves.", price: 490, veg: false },
      { id: "tandoori-fish-tikka", name: "Fish Tikka", description: "Succulent pieces of fish marinated in spices and baked in the tandoor.", price: 590, veg: false },
      { id: "tandoori-chicken-malai-tikka", name: "Chicken Malai Tikka", description: "Boneless mild chicken with a touch of ginger.", price: 460, veg: false },
      { id: "tandoori-garlic-kebab", name: "Garlic Kebab", description: "Succulent chicken pieces marinated to give a strong garlic flavour.", price: 470, veg: false },
      { id: "tandoori-chicken-tikka", name: "Chicken Tikka", description: "Boneless chicken marinated in yoghurt & spices.", price: 450, veg: false },
      { id: "tandoori-hariyali-kebab", name: "Hariyali Kebab", description: "Boneless chicken pieces marinated with crushed coriander & mint.", price: 470, veg: false },
      { id: "tandoori-chicken-half", name: "Chicken Tandoori (Half)", description: "Chicken on the bone marinated in yoghurt and spices.", price: 370, veg: false },
      { id: "tandoori-chicken-full", name: "Chicken Tandoori (Full)", description: "Chicken on the bone marinated in yoghurt and spices.", price: 590, veg: false },
      { id: "tandoori-mutton-seekh-kebab", name: "Mutton Seekh Kebab", description: "Minced mutton seasoned with spices cooked in the tandoor.", price: 570, veg: false },
    ],
  },
  {
    id: "main-course-vegetables",
    name: "Main Course — Vegetables",
    items: [
      { id: "veg-lasuni-methi-paneer", name: "Lasuni Methi Paneer", description: "A tasty combination of fenugreek, garlic, aromatic spices and cream giving this curry a complex & rich character.", price: 420, veg: true, special: true },
      { id: "veg-shaam-savera", name: "Shaam Savera", description: "Rich green kofta (shaam) stuffed with paneer (savera), blended beautifully with a rich tomato gravy.", price: 420, veg: true, special: true },
      { id: "veg-subz-diwani-handi", name: "Subz Diwani Handi", description: "A beautiful medley of lightly roasted vegetables simmered in a mildly spiced gravy made with delicate spices, herbs and nuts.", price: 420, veg: true, special: true },
      { id: "veg-lasooni-palak-beetroot-kofta", name: "Lasooni Palak Beetroot Kofta", description: "North Indian delicacy that combines the earthy sweetness of beetroot with the creamy richness of spinach infused with garlic.", price: 440, veg: true, special: true },
    ],
  },
  {
    id: "main-course-chicken",
    name: "Main Course — Chicken",
    items: [
      { id: "chicken-ghee-roast", name: "Chicken Ghee Roast", description: "A combination of succulent pieces of chicken marinated and cooked in a robust masala cooked in rich ghee, served with laccha paratha.", price: 500, veg: false, special: true },
      { id: "chicken-madras-murgh", name: "Madras Murgh", description: "A spicy, tangy, and aromatic Anglo-Indian dish characterized by a specific blend of spices, tomatoes, and coconut milk.", price: 480, veg: false, special: true },
      { id: "chicken-afghani-murgh", name: "Afghani Murgh", description: "Afghani gravy bursting with fresh flavours made from a green coriander based paste, yogurt and cream infused with minimal spices.", price: 490, veg: false, special: true },
      { id: "chicken-amritsari-murgh-masala", name: "Amritsari Murgh Masala", description: "An authentic Punjabi dish. Tender chicken chunks cooked in a rich Amritsari gravy of fresh cream, butter, tomato & spices.", price: 480, veg: false, special: true },
      { id: "chicken-murgh-dhansak", name: "Murgh Dhansak", description: "A delicious Parsi dish with super tender chicken simmered in a creamy lentil sauce bursting with aromatic spices.", price: 490, veg: false, special: true },
    ],
  },
  {
    id: "main-course-seafood",
    name: "Main Course — Seafood",
    items: [
      { id: "seafood-bihari-fish-curry", name: "Bihari Fish Curry", description: "Yellow and black mustard seeds along with coriander seeds, cumin and black pepper, roasted and ground for an extremely delicious curry.", price: 520, veg: false, special: true },
      { id: "seafood-awadhi-jheenga-curry", name: "Awadhi Jheenga Curry", description: "A royal delicacy from Awadh made with king prawns in a yogurt-based gravy with fenugreek, ginger-garlic paste, red chilli & garam masala.", price: 560, veg: false, special: true },
      { id: "seafood-chettinad-king-prawn-masala", name: "Chettinad King Prawn Masala", description: "A spicy curry from South India with big, bold flavours of roasted coriander, black pepper and fennel seeds. Perfect with steamed rice.", price: 570, veg: false, special: true },
    ],
  },
  {
    id: "main-course-mutton",
    name: "Main Course — Mutton",
    items: [
      { id: "mutton-gosht-beliram", name: "Gosht Beliram", description: "Named after the head cook in Maharaja Ranjit Singh's kitchen. Mutton chops, green chilies, spices, and yogurt, cooked slowly.", price: 600, veg: false, special: true },
      { id: "mutton-rajasthani-laal-maas", name: "Rajasthani Laal Maas", description: "\"Red Meat\" — generous amounts of red chillies, garlic & a variety of spices give this curry its distinct red colour.", price: 620, veg: false, special: true },
      { id: "mutton-home-style-aloo-gosht", name: "Home Style Aloo Gosht", description: "Succulent spiced mutton, fork-tender potatoes and a simple but aromatic gravy — a timeless classic.", price: 590, veg: false, special: true },
      { id: "mutton-keema-mutter", name: "Keema Mutter", description: "Minced mutton combined with soft peas and cooked in a delicious mixture of spices.", price: 580, veg: false, special: true },
    ],
  },
  {
    id: "mums-kitchen",
    name: "Ma Ki Rasoi Se (From Mum's Kitchen)",
    items: [
      { id: "mum-dal-fry", name: "Dal Fry", description: "Creamy, rich & smooth gravy made from masoor and moong dal.", price: 290, veg: true },
      { id: "mum-dal-makhani", name: "Dal Makhani", description: "Made with a mix of black lentils, red kidney beans & cream.", price: 380, veg: true },
      { id: "mum-aloo-mutter", name: "Aloo Mutter", description: "Potato & peas cooked together with a few spices.", price: 360, veg: true },
      { id: "mum-aloo-gobi", name: "Aloo Gobi", description: "Made with potatoes, cauliflower & Indian spices.", price: 360, veg: true },
      { id: "mum-bhindi-bhaji", name: "Bhindi Bhaji", description: "Okra dish stir fried with onions, tomatoes, herbs & spices.", price: 360, veg: true },
      { id: "mum-aloo-baingan", name: "Aloo Baingan", description: "Aubergine and potatoes simmered in a spicy tomato gravy & aromatic spices.", price: 410, veg: true },
      { id: "mum-mutter-paneer", name: "Mutter Paneer", description: "Delicious curry of peas and paneer.", price: 380, veg: true },
      { id: "mum-methi-dingri-dolma", name: "Methi Dingri Dolma", description: "Mushrooms, green peas and fenugreek leaves, simmered in a thick tomato gravy.", price: 420, veg: true },
      { id: "mum-kashmiri-dum-aloo", name: "Kashmiri Dum Aloo", description: "Slow cooked stuffed potatoes in a rich gravy.", price: 410, veg: true },
      { id: "mum-jeera-aloo", name: "Jeera Aloo", description: "A nice Indian style twist of potatoes and cumin.", price: 330, veg: true },
      { id: "mum-baingan-bharta", name: "Baingan Bharta", description: "Smoked aubergines combined with spices to form a simple, smoky-flavoured mash.", price: 430, veg: true, special: true },
      { id: "mum-palak-paneer", name: "Palak Paneer", description: "A spiced spinach based gravy with soft cottage cheese.", price: 420, veg: true },
      { id: "mum-pahadi-murgh", name: "Pahadi Murgh", description: "Chicken cooked in a yogurt gravy made by roasting & grinding an array of spices.", price: 450, veg: false },
      { id: "mum-mutton-rogan-josh", name: "Mutton Rogan Josh", description: "A fine delicacy from Kashmir which derives its name from red Kashmiri chillies.", price: 620, veg: false },
      { id: "mum-chicken-do-pyaza", name: "Chicken Do Pyaza", description: "Chicken cooked in a delicious spiced onion based gravy.", price: 450, veg: false },
      { id: "mum-nargisi-kofta", name: "Nargisi Kofta", description: "Perfectly spiced mutton keema wrapped around a hard boiled egg and braised into a rich gravy.", price: 560, veg: false },
      { id: "mum-butter-chicken", name: "Butter Chicken", description: "Boneless pieces of chicken cooked in butter, coriander, tomato and ginger.", price: 470, veg: false, special: true },
    ],
  },
  {
    id: "familiar-flavours",
    name: "Zayke Jane Pahchane (Familiar Flavours)",
    items: [
      { id: "korma-vegetable", name: "Vegetable Korma", description: "Mughlai curry with a rich sauce, spices and nuts, and a delicate hint of cardamom, rosewater and saffron.", price: 400, veg: true },
      { id: "korma-chicken", name: "Chicken Korma", description: "Mughlai curry with a rich sauce, spices and nuts, and a delicate hint of cardamom, rosewater and saffron.", price: 490, veg: false },
      { id: "mughlai-chicken", name: "Mughlai Chicken", description: "Creamy, rich, onion based curry.", price: 460, veg: false },
      { id: "mughlai-mutton", name: "Mughlai Mutton", description: "Creamy, rich, onion based curry.", price: 600, veg: false },
      { id: "kadai-vegetable", name: "Kadai Vegetable", description: "Medium spicy, made from a tomato base.", price: 360, veg: true },
      { id: "kadai-paneer", name: "Kadai Paneer", description: "Medium spicy, made from a tomato base.", price: 430, veg: true },
      { id: "kadai-chicken", name: "Kadai Chicken", description: "Medium spicy, made from a tomato base.", price: 450, veg: false },
      { id: "kadai-mutton", name: "Kadai Mutton", description: "Medium spicy, made from a tomato base.", price: 610, veg: false },
      { id: "kadai-prawn", name: "Kadai Prawn", description: "Medium spicy, made from a tomato base.", price: 520, veg: false },
      { id: "kali-mirch-mushroom", name: "Kali Mirch Mushroom", description: "Marinated with distinctive flavours of black peppercorns and curry leaves.", price: 370, veg: true },
      { id: "kali-mirch-chicken", name: "Kali Mirch Chicken", description: "Marinated with distinctive flavours of black peppercorns and curry leaves.", price: 460, veg: false },
      { id: "kali-mirch-king-prawn", name: "Kali Mirch King Prawn", description: "Marinated with distinctive flavours of black peppercorns and curry leaves.", price: 560, veg: false },
      { id: "kali-mirch-kingfish", name: "Kali Mirch Kingfish", description: "Marinated with distinctive flavours of black peppercorns and curry leaves.", price: 540, veg: false },
      { id: "jaipuri-vegetable", name: "Jaipuri Vegetable", description: "A nutritious dish from Rajasthani cuisine.", price: 370, veg: true },
      { id: "jaipuri-chicken", name: "Jaipuri Chicken", description: "A nutritious dish from Rajasthani cuisine.", price: 450, veg: false },
      { id: "jaipuri-prawn", name: "Jaipuri Prawn", description: "A nutritious dish from Rajasthani cuisine.", price: 520, veg: false },
      { id: "pasanda-paneer", name: "Paneer Pasanda", description: "Rich, creamy and mild Mughlai curry made with fragrant warming spices, coconut and cardamom.", price: 470, veg: true },
      { id: "pasanda-chicken", name: "Chicken Pasanda", description: "Rich, creamy and mild Mughlai curry made with fragrant warming spices, coconut and cardamom.", price: 490, veg: false },
      { id: "masala-paneer-butter", name: "Paneer Butter Masala", description: "Cooked in an onion/tomato gravy.", price: 450, veg: true },
      { id: "masala-egg", name: "Egg Masala", description: "Cooked in an onion/tomato gravy.", price: 360, veg: false },
      { id: "masala-chicken", name: "Chicken Masala", description: "Cooked in an onion/tomato gravy.", price: 470, veg: false },
      { id: "masala-mutton", name: "Mutton Masala", description: "Cooked in an onion/tomato gravy.", price: 600, veg: false },
      { id: "masala-prawn", name: "Prawn Masala", description: "Cooked in an onion/tomato gravy.", price: 520, veg: false },
      { id: "tikka-masala-paneer", name: "Paneer Tikka Masala", description: "Marinated chunks slow cooked in the tandoor to give a unique smoky taste before cooking further.", price: 470, veg: true },
      { id: "tikka-masala-chicken", name: "Chicken Tikka Masala", description: "Marinated chunks slow cooked in the tandoor to give a unique smoky taste before cooking further.", price: 500, veg: false },
      { id: "tikka-masala-king-prawn", name: "King Prawn Tikka Masala", description: "Marinated chunks slow cooked in the tandoor to give a unique smoky taste before cooking further.", price: 590, veg: false },
      { id: "kolhapuri-vegetable", name: "Vegetable Kolhapuri", description: "A tasty, spicy kolhapuri gravy.", price: 370, veg: true },
      { id: "kolhapuri-paneer", name: "Paneer Kolhapuri", description: "A tasty, spicy kolhapuri gravy.", price: 430, veg: true },
      { id: "kolhapuri-chicken", name: "Chicken Kolhapuri", description: "A tasty, spicy kolhapuri gravy.", price: 450, veg: false },
      { id: "kolhapuri-prawn", name: "Prawn Kolhapuri", description: "A tasty, spicy kolhapuri gravy.", price: 520, veg: false },
      { id: "jalfrezi-vegetable", name: "Vegetable Jalfrezi", description: "A spicy stir fry in a thick sauce.", price: 390, veg: true },
      { id: "jalfrezi-chicken", name: "Chicken Jalfrezi", description: "A spicy stir fry in a thick sauce.", price: 470, veg: false },
    ],
  },
  {
    id: "goan-specialties",
    name: "Goan Specialties",
    items: [
      { id: "xacuti-vegetable", name: "Vegetable Xacuti", description: "Traditional Goan preparation made with fresh coconut, red chillies, poppy seed and spices.", price: 380, veg: true },
      { id: "xacuti-chicken", name: "Chicken Xacuti", description: "Traditional Goan preparation made with fresh coconut, red chillies, poppy seed and spices.", price: 480, veg: false },
      { id: "xacuti-mutton", name: "Mutton Xacuti", description: "Traditional Goan preparation made with fresh coconut, red chillies, poppy seed and spices.", price: 610, veg: false },
      { id: "xacuti-prawn", name: "Prawn Xacuti", description: "Traditional Goan preparation made with fresh coconut, red chillies, poppy seed and spices.", price: 520, veg: false },
      { id: "caldine-vegetable", name: "Vegetable Caldine", description: "A yellow, non-spicy Goan curry made with coconut milk.", price: 400, veg: true },
      { id: "caldine-sea-bass", name: "Sea Bass (Chonak) Caldine", description: "A yellow, non-spicy Goan curry made with coconut milk.", price: 570, veg: false },
      { id: "caldine-prawn", name: "Prawn Caldine", description: "A yellow, non-spicy Goan curry made with coconut milk.", price: 520, veg: false },
      { id: "vindaloo-chicken", name: "Chicken Vindaloo", description: "Term derived from a Portuguese dish — tangy and spiced.", price: 480, veg: false },
      { id: "vindaloo-mutton", name: "Mutton Vindaloo", description: "Term derived from a Portuguese dish — tangy and spiced.", price: 610, veg: false },
      { id: "vindaloo-prawn", name: "Prawn Vindaloo", description: "Term derived from a Portuguese dish — tangy and spiced.", price: 520, veg: false },
      { id: "cafreal-chicken", name: "Chicken Cafreal", description: "A spicy preparation from Portuguese colonies in Africa.", price: 490, veg: false },
      { id: "cafreal-mutton", name: "Mutton Cafreal", description: "A spicy preparation from Portuguese colonies in Africa.", price: 610, veg: false },
      { id: "cafreal-prawn", name: "Prawn Cafreal", description: "A spicy preparation from Portuguese colonies in Africa.", price: 520, veg: false },
      { id: "goan-curry-rice-bhindi", name: "Traditional Goan Curry & Rice — Bhindi", description: "Slow cooked with fresh coconut, red chillies & spices.", price: 430, veg: true },
      { id: "goan-curry-rice-prawn", name: "Traditional Goan Curry & Rice — Prawn", description: "Slow cooked with fresh coconut, red chillies & spices.", price: 470, veg: false },
      { id: "goan-curry-rice-king-prawn", name: "Traditional Goan Curry & Rice — King Prawn", description: "Slow cooked with fresh coconut, red chillies & spices.", price: 600, veg: false },
      { id: "goan-curry-rice-fish", name: "Traditional Goan Curry & Rice — Fish", description: "Slow cooked with fresh coconut, red chillies & spices.", price: 440, veg: false },
      { id: "goan-curry-rice-kingfish", name: "Traditional Goan Curry & Rice — Kingfish", description: "Slow cooked with fresh coconut, red chillies & spices.", price: 600, veg: false },
    ],
  },
  {
    id: "chinese",
    name: "Chinese",
    items: [
      { id: "manchurian-paneer", name: "Paneer Manchurian", description: "A ginger garlic sauce.", price: 430, veg: true },
      { id: "manchurian-vegetable", name: "Vegetable Manchurian", description: "A ginger garlic sauce.", price: 410, veg: true },
      { id: "manchurian-chicken", name: "Chicken Manchurian", description: "A ginger garlic sauce.", price: 460, veg: false },
      { id: "manchurian-prawn", name: "Prawn Manchurian", description: "A ginger garlic sauce.", price: 550, veg: false },
      { id: "sweet-sour-vegetable", name: "Vegetable Sweet and Sour", description: "A sweet and sticky sauce.", price: 380, veg: true },
      { id: "sweet-sour-chicken", name: "Chicken Sweet and Sour", description: "A sweet and sticky sauce.", price: 460, veg: false },
      { id: "sweet-sour-king-prawn", name: "King Prawn Sweet and Sour", description: "A sweet and sticky sauce.", price: 570, veg: false },
      { id: "chilly-mushroom", name: "Mushroom Chilly", description: "A hot spicy sauce.", price: 390, veg: true },
      { id: "chilly-chicken", name: "Chicken Chilly", description: "A hot spicy sauce.", price: 470, veg: false },
      { id: "chilly-prawn", name: "Prawn Chilly", description: "A hot spicy sauce.", price: 510, veg: false },
    ],
  },
  {
    id: "rice-noodles",
    name: "Rice, Noodles & Biryani",
    items: [
      { id: "rice-steam", name: "Steam Rice", description: "Plain steamed basmati rice.", price: 210, veg: true },
      { id: "rice-ghee", name: "Ghee Rice", description: "Basmati rice tempered with ghee.", price: 240, veg: true },
      { id: "rice-jeera", name: "Jeera Rice", description: "Basmati rice tempered with cumin.", price: 240, veg: true },
      { id: "rice-mushroom", name: "Mushroom Rice", description: "Basmati rice with sauteed mushrooms.", price: 270, veg: true },
      { id: "rice-lemon", name: "Lemon Rice", description: "Tangy South Indian style lemon rice.", price: 260, veg: true },
      { id: "rice-veg-pulav", name: "Veg Pulav", description: "Fragrant basmati rice cooked with mixed vegetables.", price: 330, veg: true },
      { id: "rice-dal-khichidi", name: "Dal Khichidi", description: "Comforting rice and lentil khichidi.", price: 350, veg: true },
      { id: "rice-dal-khichidi-tadka", name: "Dal Khichidi Tadka", description: "Dal khichidi finished with a spiced ghee tempering.", price: 370, veg: true },
      { id: "fried-rice-vegetable", name: "Vegetable Fried Rice", description: "Wok-tossed fried rice with vegetables.", price: 300, veg: true },
      { id: "fried-rice-chicken", name: "Chicken Fried Rice", description: "Wok-tossed fried rice with chicken.", price: 350, veg: false },
      { id: "fried-rice-prawn", name: "Prawn Fried Rice", description: "Wok-tossed fried rice with prawn.", price: 370, veg: false },
      { id: "fried-rice-mixed", name: "Mixed Fried Rice", description: "Wok-tossed fried rice with chicken, prawn & egg.", price: 400, veg: false },
      { id: "schezwan-fried-rice-vegetable", name: "Schezwan Vegetable Fried Rice", description: "Fried rice tossed in spicy schezwan sauce.", price: 320, veg: true },
      { id: "schezwan-fried-rice-chicken", name: "Schezwan Chicken Fried Rice", description: "Fried rice tossed in spicy schezwan sauce.", price: 370, veg: false },
      { id: "schezwan-fried-rice-prawn", name: "Schezwan Prawn Fried Rice", description: "Fried rice tossed in spicy schezwan sauce.", price: 380, veg: false },
      { id: "schezwan-fried-rice-mixed", name: "Schezwan Mixed Fried Rice", description: "Fried rice tossed in spicy schezwan sauce.", price: 420, veg: false },
      { id: "biryani-vegetable", name: "Vegetable Biryani", description: "Fragrant basmati rice layered with spiced vegetables.", price: 380, veg: true },
      { id: "biryani-egg", name: "Egg Biryani", description: "Fragrant basmati rice layered with spiced egg.", price: 400, veg: false },
      { id: "biryani-chicken", name: "Chicken Biryani", description: "Fragrant basmati rice layered with spiced chicken.", price: 510, veg: false },
      { id: "biryani-mutton", name: "Mutton Biryani", description: "Fragrant basmati rice layered with spiced mutton.", price: 620, veg: false },
      { id: "biryani-prawn", name: "Prawn Biryani", description: "Fragrant basmati rice layered with spiced prawn.", price: 570, veg: false },
    ],
  },
  {
    id: "continental",
    name: "Continental",
    items: [
      { id: "continental-fish-chips", name: "Battered Fish & Chips", description: "Classic British fish and chips served with homemade tartar sauce and chips.", price: 520, veg: false },
      { id: "continental-chicken-chips", name: "Chicken & Chips", description: "Deep fried chicken strips covered in bread crumbs served with chips.", price: 470, veg: false },
    ],
  },
  {
    id: "sizzlers",
    name: "Sizzlers",
    note: "All sizzlers are served with chips, rice and vegetables.",
    items: [
      { id: "sizzler-paneer-tikka", name: "Paneer Tikka Sizzler", description: "Paneer tikka served sizzling with chips, rice and vegetables.", price: 500, veg: true },
      { id: "sizzler-chicken-tikka", name: "Chicken Tikka Sizzler", description: "Chicken tikka served sizzling with chips, rice and vegetables.", price: 520, veg: false },
      { id: "sizzler-king-prawn-tikka", name: "King Prawn Tikka Sizzler", description: "King prawn tikka served sizzling with chips, rice and vegetables.", price: 630, veg: false },
    ],
  },
  {
    id: "platters",
    name: "Platters",
    items: [
      { id: "platter-seafood", name: "Seafood Platter", description: "Whole pomfret/sea bass, tiger prawn, calamari, mackerel and white fish, served with chips.", price: 3300, veg: false, special: true },
      { id: "platter-la-ben-tandoori", name: "La Ben Tandoori Platter", description: "Half chicken tandoori, chicken seekh kebab & chicken tikka, served with plain naan.", price: 1150, veg: false, special: true },
    ],
  },
  {
    id: "seafood-alacarte",
    name: "Seafood",
    note: "Pomfret, Red Snapper, Baby Kingfish, Tiger Prawns & Crabs are priced as per size on the day's catch — ask our team when you call in your order.",
    items: [
      { id: "seafood-calamari", name: "Calamari", description: "Cooked as per your choice, served with a generous portion of fries and salad.", price: 520, veg: false },
      { id: "seafood-king-fish", name: "King Fish", description: "Cooked as per your choice, served with a generous portion of fries and salad.", price: 600, veg: false },
    ],
  },
  {
    id: "indian-bread",
    name: "Indian Bread",
    items: [
      { id: "roti-plain", name: "Plain Roti", description: "Whole wheat bread.", price: 70, veg: true },
      { id: "roti-butter", name: "Butter Roti", description: "Whole wheat bread brushed with butter.", price: 90, veg: true },
      { id: "roti-methi", name: "Methi Roti", description: "Whole wheat bread with fenugreek leaves.", price: 100, veg: true },
      { id: "roti-mint", name: "Mint Roti", description: "Whole wheat bread with mint.", price: 100, veg: true },
      { id: "kulcha-plain", name: "Plain Kulcha", description: "Leavened bread baked in the tandoor.", price: 100, veg: true },
      { id: "kulcha-onion", name: "Onion Kulcha", description: "Kulcha stuffed with spiced onion.", price: 170, veg: true },
      { id: "kulcha-masala", name: "Masala Kulcha", description: "Kulcha stuffed with spiced masala.", price: 170, veg: true },
      { id: "kulcha-paneer", name: "Paneer Kulcha", description: "Kulcha stuffed with spiced paneer.", price: 220, veg: true },
      { id: "paratha-lacha", name: "Lacha Paratha", description: "Multi-layered, flaky whole wheat bread.", price: 120, veg: true },
      { id: "paratha-mint", name: "Mint Paratha", description: "Multi-layered paratha with mint.", price: 120, veg: true },
      { id: "paratha-aloo", name: "Aloo Paratha", description: "Paratha stuffed with spiced potato.", price: 210, veg: true },
      { id: "paratha-aloo-methi", name: "Aloo Methi Paratha", description: "Paratha stuffed with spiced potato and fenugreek.", price: 230, veg: true },
      { id: "naan-plain", name: "Plain Naan", description: "Leavened bread baked in the tandoor.", price: 100, veg: true },
      { id: "naan-butter", name: "Butter Naan", description: "Naan brushed with butter.", price: 110, veg: true },
      { id: "naan-garlic", name: "Garlic Naan", description: "Naan topped with fresh garlic.", price: 180, veg: true },
      { id: "naan-cheese", name: "Cheese Naan", description: "Naan stuffed with cheese.", price: 205, veg: true },
      { id: "naan-cheese-chilly", name: "Cheese Chilly Naan", description: "Naan stuffed with cheese and chilli.", price: 210, veg: true },
      { id: "naan-cheese-garlic", name: "Cheese Garlic Naan", description: "Naan stuffed with cheese and garlic.", price: 210, veg: true },
      { id: "naan-cheese-onion", name: "Cheese Onion Naan", description: "Naan stuffed with cheese and onion.", price: 220, veg: true },
      { id: "naan-cheese-tomato", name: "Cheese Tomato Naan", description: "Naan stuffed with cheese and tomato.", price: 220, veg: true },
      { id: "naan-cheese-chilly-garlic", name: "Cheese Chilly Garlic Naan", description: "Naan stuffed with cheese, chilli and garlic.", price: 240, veg: true },
      { id: "naan-peshawari", name: "Peshawari Naan", description: "Naan stuffed with dried fruit and nuts.", price: 250, veg: true },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    items: [
      { id: "dessert-bebinca", name: "Bebinca", description: "A traditional Indo-Portuguese layered cake served with a scoop of vanilla ice cream.", price: 210, veg: false },
      { id: "dessert-brownie", name: "Brownie", description: "A rich, gooey chocolatey brownie with nuts, served warm with vanilla ice cream.", price: 250, veg: false },
      { id: "dessert-banana-split", name: "Banana Split", description: "Ice cream served between bananas sliced lengthways, garnished with chocolate syrup, raisins and cashew nut.", price: 270, veg: false },
      { id: "dessert-banana-fritters", name: "Banana Fritters", description: "Banana chunks battered and deep fried, served with a generous drizzle of honey.", price: 175, veg: false },
      { id: "dessert-fruit-salad", name: "Fruit Salad", description: "A delicious and refreshing combination of fresh seasonal fruit.", price: 260, veg: true },
      { id: "dessert-banofee-pie", name: "Banofee Pie", description: "A biscuit base topped with a thick, gooey banana caramel filling.", price: 270, veg: true },
      { id: "dessert-tiramisu", name: "Tiramisu", description: "An Italian dessert made of sponge dipped in coffee liquor, layered with a whipped mix of egg yolks, sugar, and mascarpone.", price: 190, veg: false },
      { id: "pancake-plain", name: "Plain Pancakes", description: "Classic pancakes.", price: 120, veg: false },
      { id: "pancake-banana", name: "Banana Pancakes", description: "Pancakes with banana.", price: 135, veg: false },
      { id: "pancake-chocolate", name: "Chocolate Pancakes", description: "Pancakes with chocolate.", price: 155, veg: false },
      { id: "pancake-honey", name: "Honey Pancakes", description: "Pancakes drizzled with honey.", price: 160, veg: false },
      { id: "ice-cream-vanilla", name: "Vanilla Ice Cream", description: "Classic vanilla ice cream.", price: 170, veg: true },
      { id: "ice-cream-chocolate", name: "Chocolate Ice Cream", description: "Rich chocolate ice cream.", price: 170, veg: true },
      { id: "ice-cream-butterscotch", name: "Butterscotch Ice Cream", description: "Butterscotch ice cream.", price: 170, veg: true },
    ],
  },
  {
    id: "tea-coffee",
    name: "Tea & Coffee",
    items: [
      { id: "tea-pot", name: "Pot Tea", description: "A pot of freshly brewed tea.", price: 150, veg: true },
      { id: "tea-pot-milk", name: "Pot Milk Tea", description: "A pot of tea served with milk.", price: 170, veg: true },
      { id: "tea-pot-masala", name: "Pot Masala Tea", description: "Spiced Indian tea.", price: 220, veg: true },
      { id: "tea-pot-ginger", name: "Pot Ginger Tea", description: "Tea brewed with fresh ginger.", price: 250, veg: true },
      { id: "coffee-pot", name: "Pot Coffee", description: "A pot of freshly brewed coffee.", price: 150, veg: true },
      { id: "coffee-pot-milk", name: "Pot Milk Coffee", description: "A pot of coffee served with milk.", price: 170, veg: true },
    ],
  },
  {
    id: "soft-drinks-juices",
    name: "Soft Drinks & Juices",
    items: [
      { id: "drink-red-bull", name: "Red Bull", description: "Energy drink.", price: 150, veg: true },
      { id: "drink-bitter-lemon", name: "Bitter Lemon", description: "Sparkling bitter lemon mixer.", price: 130, veg: true },
      { id: "drink-ginger-ale", name: "Ginger Ale", description: "Sparkling ginger ale.", price: 100, veg: true },
      { id: "drink-tonic-water", name: "Tonic Water", description: "Sparkling tonic water.", price: 100, veg: true },
      { id: "drink-diet-coke", name: "Diet Coke", description: "Diet cola.", price: 100, veg: true },
      { id: "drink-kokam-soda", name: "Kokam Soda", description: "Tangy Goan kokam soda.", price: 90, veg: true },
      { id: "drink-coke", name: "Coke", description: "Classic cola.", price: 30, veg: true },
      { id: "drink-sprite", name: "Sprite", description: "Lemon-lime soda.", price: 30, veg: true },
      { id: "drink-fanta", name: "Fanta", description: "Orange soda.", price: 30, veg: true },
      { id: "drink-thumbs-up", name: "Thumbs Up", description: "Classic Indian cola.", price: 30, veg: true },
      { id: "drink-mineral-water", name: "Mineral Water", description: "Bottled mineral water.", price: 30, veg: true },
      { id: "drink-soda", name: "Soda", description: "Plain soda water.", price: 20, veg: true },
      { id: "juice-orange", name: "Cold Press Orange Juice", description: "Freshly cold-pressed orange juice.", price: 280, veg: true },
      { id: "juice-pineapple", name: "Cold Press Pineapple Juice", description: "Freshly cold-pressed pineapple juice.", price: 220, veg: true },
      { id: "juice-watermelon", name: "Cold Press Watermelon Juice", description: "Freshly cold-pressed watermelon juice.", price: 220, veg: true },
      { id: "drink-jaljeera", name: "Jaljeera", description: "Tangy cumin and mint cooler.", price: 80, veg: true },
      { id: "drink-masala-cold-drink", name: "Masala Cold Drink", description: "Spiced cold drink.", price: 90, veg: true },
      { id: "drink-buttermilk", name: "Buttermilk", description: "Spiced chilled buttermilk.", price: 120, veg: true },
      { id: "lassi-banana", name: "Banana Lassi", description: "Yogurt drink blended with banana.", price: 150, veg: true },
      { id: "lassi-mango", name: "Mango Lassi", description: "Yogurt drink blended with mango.", price: 170, veg: true },
      { id: "lassi-sweet-salted", name: "Lassi (Sweet or Salted)", description: "Classic yogurt drink, sweet or salted.", price: 130, veg: true },
    ],
  },
  {
    id: "mocktails",
    name: "Mocktails",
    items: [
      { id: "mocktail-virgin-colada", name: "Virgin Colada", description: "Pineapple juice, coconut cream.", price: 270, veg: true },
      { id: "mocktail-after-glow", name: "After Glow", description: "7up, grenadine, blue curacao, squeeze of lime.", price: 270, veg: true },
      { id: "mocktail-tropical-sun", name: "Tropical Sun", description: "Orange, mango and banana juices with grenadine.", price: 270, veg: true },
      { id: "mocktail-mickey-mouse", name: "Mickey Mouse", description: "Cola topped with ice cream.", price: 270, veg: true },
      { id: "mocktail-virgin-mary", name: "Virgin Mary", description: "Tomato juice, Worcestershire sauce, lime juice and seasoning.", price: 270, veg: true },
      { id: "mocktail-big-wave", name: "Big Wave", description: "Pineapple, blue curacao and cream.", price: 270, veg: true },
      { id: "mocktail-old-peruwala", name: "Old Peruwala", description: "Guava, lime juice and a pinch of chilly.", price: 270, veg: true },
    ],
  },
];

export const allMenuItems: MenuItem[] = menu.flatMap((c) => c.items);
export const findMenuItem = (id: string) => allMenuItems.find((i) => i.id === id);
